---
  # Gluster volume configuration.
  - name: Check if Gluster volumes already exist.
    shell: "gluster volume info"
    changed_when: false
    register: gluster_volume_info_check

  - name: Connect to Gluster peers.
    shell: "gluster peer probe {{ gluster_peer }}"
    register: gluster_peer_probe
    when: "'Volume Name: aegir' not in gluster_volume_info_check.stdout"
    failed_when: false

  # Make sure the brick directory exists
  - file: path=/mnt/aegirvolume/glusterbrick state=directory

  - name: Create gluster volume
    gluster_volume: state=present name=aegirvolume brick=/mnt/aegirvolume/glusterbrick cluster="{{ gluster_peer }}"
    when: "'Volume Name: aegir' not in gluster_volume_info_check.stdout"
    register: gluster_volumed_created

  - name: Start gluster volume
    gluster_volume: state=started name=aegirvolume
    register: gluster_volume_started

  ## Set gluster things here
  - shell: "gluster volume set aegirvolume storage.owner-uid 2160"
    changed_when: false
  - shell: "gluster volume set aegirvolume storage.owner-gid 2160"
    changed_when: false

  # Mounting the volume as localhost
  - name: Mount Aegir directory
    mount: name=/var/aegir src='127.0.0.1:/aegirvolume' fstype=glusterfs state=present
    when: gluster_volume_started
