---
- name: Verify default congiguration
  hosts: all
  become: yes
  vars_files:
    - ../ansible-dev-vars.yml

  pre_tasks:
    - name: Add apt key for PHP
      apt_key: url=https://packages.sury.org/php/apt.gpg state=present
    - name: Add repository for PHP
      apt_repository: repo='deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main' update_cache=yes state=present

    - name: Add apt key for nginx
      apt_key: url=http://nginx.org/keys/nginx_signing.key state=present
    - name: Add repository for nginx
      apt_repository: repo='deb http://nginx.org/packages/debian/ {{ ansible_distribution_release }} nginx' update_cache=yes state=present

    - name: Ensure apt.conf exists
      shell: "touch /etc/apt/apt.conf creates=/etc/apt/apt.conf" 

    - name: Don't install recommended packages
      lineinfile:
        dest: /etc/apt/apt.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - regexp: "^APT::Get::Install-Recommends.+$"
          line: "APT::Get::Install-Recommends \"false\";"
        - regexp: "^APT::Get::Install-Suggests.+$"
          line: "APT::Get::Install-Suggests \"false\";"

    - name: Update all default packages
      apt: update_cache=yes upgrade=dist

    - include: tasks/aegir-user.yml

    - file: path={{ nginx_conf_path }}/aegir.conf state=absent

    # Make sure the ebs is mounted
    - file: path={{ ebs_mount_dir }} state=directory
    - filesystem: fstype=ext4 dev=/dev/xvdh opts="-c" resizefs=yes
    - mount: name={{ ebs_mount_dir }} src=/dev/xvdh fstype=ext4 opts=defaults passno=2 state=mounted

  roles:
    - common
    - nginx
    - { role: tersmitten.swapfile, swapfile_size: 4GiB, swapfile_file: "/swap" }
    - tersmitten.postfix
    - geerlingguy.git
    - geerlingguy.postfix
    - geerlingguy.nginx
    - geerlingguy.nodejs
    - geerlingguy.php
    - geerlingguy.php-pecl
    - geerlingguy.php-mysql
    - geerlingguy.php-pecl
    - geerlingguy.php-memcached
    - geerlingguy.php-redis
    - geerlingguy.security

  tasks:
    - name: Set php-cli version
      become: yes
      shell: update-alternatives --set php /usr/bin/php7.0

    - name: Disable php5.6-fpm
      become: yes
      systemd: name=php5.6-fpm enabled=no masked=yes state=stopped

    - name: Enable php7.0-fpm
      become: yes
      systemd: name=php7.0-fpm enabled=yes masked=no state=started

    - name: Remove conflicting configuration from Geerlingguy's template
      lineinfile:
        dest: '{{ nginx_conf_file_path }}'
        line: '{{ item }}'
        state: absent
      with_items:
        - "    server_names_hash_bucket_size 64;"
        - "    log_format  main  '$remote_addr - $remote_user [$time_local] \"$request\" '"
        - "                      '$status $body_bytes_sent \"$http_referer\" '"
        - "                      '\"$http_user_agent\" \"$http_x_forwarded_for\"';"
        - "    access_log  {{ nginx_access_log }};"

    - name: Check symbolic link to Aegir's NGINX Config
      file:
        src: "{{ aegir_user_home }}/config/nginx.conf"
        dest: "{{ nginx_conf_path }}/aegir.conf"
        state: link
        force: yes
      notify:
        - reload nginx

    - name: Update required drush packages.
      command: "drush dl {{ item.key }}-{{ item.value }} --destination={{ aegir_user_home }}/.drush -y"
      with_dict: "{{ aegir_drush_packages }}"
      become: yes
      become_user: "{{ aegir_user_name }}"

    - name: download provision patch
      get_url:
        url: https://www.drupal.org/files/issues/2829411-18.patch
        dest: "{{ aegir_user_home }}/2829411-18.patch"

    - name: apply provision patch
      patch: >
        src="{{ aegir_user_home }}/2829411-18.patch"
        basedir="{{ aegir_user_home }}/.drush/provision"
        remote_src=yes
        strip=1

    - name: Update makefile
      template:
        src: roles/aegir3-nginx/templates/aegir.make.yml.j2
        dest: "{{ aegir_user_home }}/aegir.make.yml"
        owner: "{{ aegir_user_name }}"
        group: "{{ aegir_user_name }}"
        force: yes
        mode: 0644

    # - name: Update hostmaster.
    #   command: "drush @hm hostmaster-migrate --http_service_type=nginx --makefile={{ aegir_user_home }}/aegir.make.yml {{ aegir_master_domain }} {{ aegir_user_home }}/hostmaster-{{ 2147483647 | random | to_uuid }} -y"
    #   become: yes
    #   become_user: "{{ aegir_user_name }}"
