---
- name: Verify default congiguration
  hosts: 
    - gluster
  become: yes
  vars_files:
    - vars/main.yml

  pre_tasks:
    # Make sure the ebs is mounted
    - file: path={{ ebs_mount_dir }} state=directory
    - mount: name={{ ebs_mount_dir }} src=/dev/xvdh fstype=ext4 opts=defaults passno=2 state=mounted
    # Make sure that the mount point exists
    - file: path={{ gluster_brick_dir }} state=directory
    - file: path={{ gluster_mount_dir }} state=directory owner="aegir" group="aegir"
    - name: Add apt key for gluster
      apt_key: url=http://download.gluster.org/pub/gluster/glusterfs/LATEST/rsa.pub state=present
    - name: Add repository for gluster
      apt_repository: repo='deb https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/{{ ansible_distribution_release }}/apt {{ ansible_distribution_release }} main' update_cache=yes state=present

  roles:
    - geerlingguy.glusterfs
    - { role: tersmitten.swapfile, swapfile_size: 4GiB, swapfile_file: "{{ ebs_mount_dir }}/swap" }

  tasks:
    - name: Configure Gluster volume.
      gluster_volume:
        state: present
        name: "{{ gluster_brick_name }}"
        brick: "{{ gluster_brick_dir }}"
        replicas: 2
        cluster: "{{ groups.gluster | join(',') }}"
        host: "{{ inventory_hostname }}"
        force: yes
      run_once: true

    - name: Ensure Gluster volume is mounted.
      mount:
        name: "{{ gluster_mount_dir }}"
        src: "{{ inventory_hostname }}:/{{ gluster_brick_name }}"
        fstype: glusterfs
        opts: "defaults,_netdev"
        state: mounted