---
- hosts: all
  roles:
    - common
    - efs
    - nginx
  sudo: yes

- hosts: aegir3-webnode
  roles:
    - {role: aegir3-saas, tags: saas}
  sudo: yes

- hosts: aegir3-hub
  roles:
    - {role: aegir3-saas-hub, tags: hub}
  sudo: yes
