---
- hosts: all
  roles:
    - common
  sudo: yes

- hosts: mysql-servers
  roles:
    - mysql-server

- hosts: aegir3
  roles:
    - aegir3-nginx

- hosts: aegir3-saas
  roles:
      - {role: aegir3-saas, tags: saas}

- hosts: aegir3-saas-hub
  roles:
      - {role: aegir3-saas-hub, tags: hub}
