---
- hosts: all
  become: yes
  vars_files:
    - ../ansible-vars.yml

  pre_tasks:
    # php repo
    - name: Add apt key for Debian
      apt_key: url=https://packages.sury.org/php/apt.gpg state=present
    - name: Add repository for PHP
      apt_repository: repo='deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main' update_cache=yes state=present

    # nginx repo
    - name: Add apt key for nginx
      apt_key: url=http://nginx.org/keys/nginx_signing.key state=present
    - name: Add repository for nginx
      apt_repository: repo='deb http://nginx.org/packages/debian/ {{ ansible_distribution_release }} nginx' update_cache=yes state=present

    # fix apt.conf
    - name: Ensure apt.conf exists
      shell: touch /etc/apt/apt.conf creates=/etc/apt/apt.conf 
    - name: Don't install recommended packages
      lineinfile:
        dest: /etc/apt/apt.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - regexp: "^APT::Get::Install-Recommends.+$"
          line: "APT::Get::Install-Recommends \"false\";"
        - regexp: "^APT::Get::Install-Suggests.+$"
          line: "APT::Get::Install-Suggests \"false\";"

    - name: Update all default packages
      apt: update_cache=yes upgrade=dist

    - include: tasks/aegir-user.yml

  roles:
    - common
    - tersmitten.postfix
    - geerlingguy.git
    - geerlingguy.postfix
    - geerlingguy.nginx
    - geerlingguy.nodejs
    - geerlingguy.php
    - geerlingguy.php-pecl
    - geerlingguy.php-mysql
    - geerlingguy.php-pecl
    - geerlingguy.php-memcached
    - geerlingguy.php-redis
    - geerlingguy.security

  tasks:
    - name: Set php-cli version
      become: yes
      shell: update-alternatives --set php /usr/bin/php5.6

- hosts: all
  become: yes
  vars_files:
    - ../ansible-vars.yml
  roles:
    - geerlingguy.composer
    - geerlingguy.drush
    - geerlingguy.drupal-console
    - franklinkim.newrelic
    - franklinkim.php5-newrelic
