---
- src: javaguirre.drupal_deps
- src: franklinkim.newrelic
  version: 1.4.0
- src: geerlingguy.composer
  version: 1.4.1
- src: geerlingguy.daemonize
  version: 1.1.0
- src: geerlingguy.drupal-console
  version: 1.0.7
- src: geerlingguy.drush
  version: 1.1.3
- src: geerlingguy.git
  version: 1.1.1
- src: geerlingguy.nginx
  version: 1.9.3
- src: geerlingguy.nodejs
  version: 3.2.0
- src: geerlingguy.php
  version: 3.2.2
- src: geerlingguy.php-memcached
  version: 2.0.0
- src: geerlingguy.php-mysql
  version: 2.0.0
- src: geerlingguy.php-pecl
  version: 1.2.1
- src: geerlingguy.php-redis
  version: 3.0.0
- src: geerlingguy.postfix
  version: 1.1.0
- src: geerlingguy.security
  version: 1.4.0
- src: geerlingguy.glusterfs
  version: 2.1.0
- src: tersmitten.swapfile
  version: 1.0.2
