---
- name: Verify default congiguration
  hosts: all
  become: yes
  vars_files:
    - ../ansible-vars.yml

  pre_tasks:
    - name: Add apt key for PHP
      apt_key: url=https://packages.sury.org/php/apt.gpg state=present
    - name: Add repository for PHP
      apt_repository: repo='deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main' update_cache=yes state=present

    - name: Add apt key for nginx
      apt_key: url=http://nginx.org/keys/nginx_signing.key state=present
    - name: Add repository for nginx
      apt_repository: repo='deb http://nginx.org/packages/debian/ {{ ansible_distribution_release }} nginx' update_cache=yes state=present

    - name: Add apt key for gluster
      apt_key: url=http://download.gluster.org/pub/gluster/glusterfs/3.8/LATEST/rsa.pub state=present
    - name: Add repository for gluster
      apt_repository: repo='deb https://download.gluster.org/pub/gluster/glusterfs/3.8/LATEST/Debian/{{ ansible_distribution_release }}/apt {{ ansible_distribution_release }} main' update_cache=yes state=present

    - name: Ensure apt.conf exists
      shell: "touch /etc/apt/apt.conf creates=/etc/apt/apt.conf" 

    - name: Don't install recommended packages
      lineinfile:
        dest: /etc/apt/apt.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - regexp: "^APT::Get::Install-Recommends.+$"
          line: "APT::Get::Install-Recommends \"false\";"
        - regexp: "^APT::Get::Install-Suggests.+$"
          line: "APT::Get::Install-Suggests \"false\";"

    - name: Update all default packages
      apt: update_cache=yes upgrade=dist

    - include: tasks/aegir-user.yml

    # Make sure the ebs is mounted
    - file: path={{ ebs_mount_dir }} state=directory
    - mount: name={{ ebs_mount_dir }} src=/dev/xvdh fstype=ext4 opts=defaults passno=2 state=mounted
    # Make sure that the mount point exists
    - file: path={{ gluster_brick_dir }} state=directory
    - file: path={{ gluster_mount_dir }} state=directory owner="aegir" group="aegir"

  roles:
    - common
    - geerlingguy.glusterfs
    - { role: tersmitten.swapfile, swapfile_size: 4GiB, swapfile_file: "{{ ebs_mount_dir }}/swap" }
    - tersmitten.postfix
    - geerlingguy.git
    - geerlingguy.postfix
    - geerlingguy.nginx
    - geerlingguy.nodejs
    - geerlingguy.php
    - geerlingguy.php-pecl
    - geerlingguy.php-mysql
    - geerlingguy.php-pecl
    - geerlingguy.php-memcached
    - geerlingguy.php-redis
    - geerlingguy.composer
    - geerlingguy.drush
    - geerlingguy.drupal-console
    - franklinkim.newrelic
    - franklinkim.php5-newrelic
    - geerlingguy.security

  tasks:
    - name: Set php-cli version
      become: yes
      shell: update-alternatives --set php /usr/bin/php5.6

    - name: Remove conflicting configuration from Geerlingguy's template
      lineinfile:
        dest: '{{ nginx_conf_file_path }}'
        line: '{{ item }}'
        state: absent
      with_items:
        - "    server_names_hash_bucket_size 64;"
        - "    log_format  main  '$remote_addr - $remote_user [$time_local] \"$request\" '"
        - "                      '$status $body_bytes_sent \"$http_referer\" '"
        - "                      '\"$http_user_agent\" \"$http_x_forwarded_for\"';"
        - "    access_log  {{ nginx_access_log }};"
      notify:
        - reload nginx