---
  - name: Figure out the hostmaster root
    shell: "drush @hostmaster status |grep 'Drupal root' |awk '{ print $NF }'"
    register: aegir_siteroot
    become: yes
    become_user: "{{ aegir_user_name }}"
    changed_when: False

  - debug: msg={{ aegir_siteroot.stdout }}

  - name: Download the SaaS modules from drupal.org
    shell: drush @hm dl -y {{ drush_dl | join(" ") }}
    args:
      chdir: '{{ aegir_siteroot.stdout }}/sites/{{ hostmaster_fqdn }}'
    become: yes
    become_user: "{{ aegir_user_name }}"

  - name: Enable all modules
    shell: drush @hm en -y {{ drush_en | join(" ") }}
    become: yes
    become_user: "{{ aegir_user_name }}"

  - name: Clear the drush cache
    shell: drush cc drush
    become: yes
    become_user: "{{ aegir_user_name }}"

  - name: Create folder for lets encrypt
    file:
      path: "{{ aegir_user_home }}/tools/le/.ctrl"
      owner: "{{ aegir_user_name }}"
      group: "{{ aegir_user_name }}"
      mode: 0744
      state: directory

  - name: Set up lets encrypt pidfile
    shell: "touch {{ aegir_user_home }}/tools/le/.ctrl/ssl-demo-mode.pid creates={{ aegir_user_home }}/tools/le/.ctrl/ssl-demo-mode.pid" 

  - name: Download lets encrypt
    get_url:
      url: https://raw.githubusercontent.com/omega8cc/letsencrypt.sh/master/letsencrypt.sh
      dest: "{{ aegir_user_home }}/tools/le/letsencrypt.sh"
      owner: "{{ aegir_user_name }}"
      group: "{{ aegir_user_name }}"
      mode: 700

  # This is not used here, it's used when we aggregate this info on the hub.
  - name: Get credentials for remote authentication
    script: ./generate_credentials.sh
    become: yes
    become_user: "{{ aegir_user_name }}"
    changed_when: False
    register: network_node_credentials

  - debug: var=network_node_credentials
