---
  - name: Figure out the hostmaster root
    shell: "drush @hostmaster status |grep 'Drupal root' |awk '{ print $NF }'"
    register: aegir_siteroot
    become: yes
    become_user: "{{ aegir_user_name }}"
    changed_when: False

  - name: Download the SaaS modules from drupal.org
    shell: drush @hm dl -y {{ drush_dl | join(" ") }}
    args:
      chdir: '{{ aegir_siteroot.stdout }}/sites/{{ hostmaster_fqdn }}'
    become: yes
    become_user: "{{ aegir_user_name }}"

  - name: Enable all modules
    shell: drush @hm en -y {{ drush_en | join(" ") }}
    become: yes
    become_user: "{{ aegir_user_name }}"

  - name: Clear the drush cache
    shell: drush cc drush
    become: yes
    become_user: "{{ aegir_user_name }}"

  # This is not used here, it's used when we aggregate this info on the hub.
  - name: Get credentials for remote authentication
    script: ./generate_credentials.sh
    become: yes
    become_user: "{{ aegir_user_name }}"
    changed_when: False
    register: network_node_credentials

  - debug: var=network_node_credentials
    when: network_node_credentials.exists
