---
- name: Start webserver
  service: name=nginx state=started

- name: Reload webserver
  service: name=nginx state=reloaded

- name: Restart webserver
  service: name=nginx state=restarted

- name: restart nginx
  command: /bin/true
  changed_when: true
  notify: remove nginx.conf bad lines

- name: validate nginx configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: False

- name: reload nginx
  command: /bin/true
  changed_when: true
  notify: remove nginx.conf bad lines

- name: remove nginx.conf bad lines
  lineinfile:
    dest: '{{ nginx_conf_file_path }}'
    line: '{{ item }}'
    state: absent
  with_items:
    - "    server_names_hash_bucket_size {{ nginx_server_names_hash_bucket_size }};"
    - "    client_max_body_size {{ nginx_client_max_body_size }};"
    - "    log_format  main  '$remote_addr - $remote_user [$time_local] \"$request\" '"
    - "                      '$status $body_bytes_sent \"$http_referer\" '"
    - "                      '\"$http_user_agent\" \"$http_x_forwarded_for\"';"
    - "    access_log  {{ nginx_access_log }};"
  notify: add nginx module includes

- name: add nginx module includes
  lineinfile:
    dest: '{{ nginx_conf_file_path }}'
    line: '{{ item }}'
    insertbefore: BOF
    state: present
  with_items:
    - "load_module modules/ngx_http_geoip_module.so;"
