---
# tasks file for swapfile
- name: write swap file
  command: "fallocate -l {{ swapfile_size }} {{ swapfile_file }}"
  args:
    creates: "{{ swapfile_file }}"
  register: write_swapfile
  when: swapfile_size != false
  tags: [configuration, swapfile]

- name: set swap file permissions
  file:
    path: "{{ swapfile_file }}"
    owner: root
    group: root
    mode: 0600
  when: swapfile_size != false
  tags: [configuration, swapfile]

- name: create swap file
  command: "mkswap {{ swapfile_file }}"
  register: create_swapfile
  when: swapfile_size != false and write_swapfile.changed
  tags: [configuration, swapfile]

- name: enable swapfile
  command: "swapon {{ swapfile_file }}"
  when: swapfile_size != false and create_swapfile.changed
  tags: [configuration, swapfile]

- name: add swapfile to /etc/fstab
  mount:
    name: none
    src: "{{ swapfile_file }}"
    fstype: swap
    opts: sw
    passno: '0'
    dump: '0'
    state: present
  tags: [configuration, swapfile]

- name: configure vm.swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ swapfile_swappiness }}"
    reload: true
    state: present
  when: swapfile_swappiness != false
  tags: [configuration, swapfile]

- name: configure vm.vfs_cache_pressure
  sysctl:
    name: vm.vfs_cache_pressure
    value: "{{ swapfile_vfs_cache_pressure }}"
    reload: true
    state: present
  when: swapfile_vfs_cache_pressure != false
  tags: [configuration, swapfile]
