---
  - name: Install common packages
    apt: pkg={{ item }} state=installed update_cache=true
    with_items:
      - curl
      - fail2ban
      - git
      - htop
      - ntp
      - npm
      - tree
      - vim

  - name: Install gluster and partitioning packages
    apt: pkg={{ item }} state=installed update_cache=true
    with_items:
      - xfsprogs
      - glusterfs-common
      - glusterfs-server
