---
  - name: Install common packages
    apt: pkg={{ item }} state=installed update_cache=true
    with_items:
      - build-essential
      - curl
      - htop
      - ntp
      - openssl
      - tree
      - vim
      - mariadb-client-10.0
