---
  # We assume that this runs after the original has created the node.

  # Create the Aegir group preemptively so we can mount the directory with it
  - name: Ensure Aegir group exists
    group: name=aegir gid=2160 state=present

  # Create the Aegir user preemptively so we can mount the directory with it
  - name: Ensure Aegir user exists
    user: name=aegir group=aegir groups=www-data uid=2160 shell=/bin/bash home=/var/aegir

  # Gluster volume configuration.
  - name: Check if EBS volume is empty
    shell: "file -s /dev/xvdh"
    changed_when: false
    register: ebs_volume_check

  - name: Format EBS volume if necessary
    when: "'/dev/xvdh: data' in ebs_volume_check.stdout"
    shell: "mkfs -t ext4 /dev/xvdh"

  # Make sure the mounting directory exists
  - file: path=/mnt/aegirvolume state=directory

  # For some reason the mount module is failing us here.
  - name: Mount EBS volume
    shell: mount /dev/xvdh /mnt/aegirvolume
    register: ebs_volume_mounted
    failed_when: ("ebs_volume_mounted.stderr!=''") and ("'already' not in ebs_volume_mounted.stdout")
    ignore_errors: true

  # Make sure the brick directory exists
  - file: path=/mnt/aegirvolume/glusterbrick state=directory

  # Mounting the volume as localhost
  - name: Mount Aegir directory
    mount: name=/var/aegir src='127.0.0.1:/aegirvolume' fstype=glusterfs state=present
