---
  - name: Check if Aegir is installed
    stat: 
      path: "{{ aegir_user_home }}/config"
    register: aegir_installed

  - include: install_aegir.yml
    when: not aegir_installed.stat.exists

  - name: Copy queued service definition
    shell: "cp {{ aegir_user_home }}/.drush/provision/debian/aegir3-hostmaster.hosting-queued.service /lib/systemd/system/hosting-queued.service creates=/lib/systemd/system/hosting-queued.service"
    become: yes

  - name: Enable queued service
    service: name=hosting-queued enabled=yes state=started
    become: yes

  - name: Create folder for lets encrypt
    file:
      path: "{{ aegir_user_home }}/tools/le"
      owner: "{{ aegir_user_name }}"
      group: "{{ aegir_user_name }}"
      mode: 0755
      state: directory

  - name: Create folder for lets encrypt pid files
    file:
      path: "{{ aegir_user_home }}/tools/le/.ctrl"
      owner: "{{ aegir_user_name }}"
      group: "{{ aegir_user_name }}"
      mode: 0755
      state: directory

  - name: Download lets encrypt
    get_url:
      url: https://raw.githubusercontent.com/omega8cc/letsencrypt.sh/master/letsencrypt.sh
      dest: "{{ aegir_user_home }}/tools/le/letsencrypt.sh"
      owner: "{{ aegir_user_name }}"
      group: "{{ aegir_user_name }}"
      mode: 0700
