---
  - name: Remove conflicting configuration from Geerlingguy's template.    server_names_hash_bucket_size 64;
    lineinfile:
      dest: '{{ nginx_conf_file_path }}'
      line: '{{ item }}'
      state: absent
    with_items:
      - "    server_names_hash_bucket_size 64;"
      - "    log_format  main  '$remote_addr - $remote_user [$time_local] \"$request\" '"
      - "                      '$status $body_bytes_sent \"$http_referer\" '"
      - "                      '\"$http_user_agent\" \"$http_x_forwarded_for\"';"
      - "    access_log  {{ nginx_access_log }};"

  - name: "Set hosts file"
    lineinfile: dest=/etc/hosts regexp='.* {{ hostmaster_fqdn }}$' line="{{ hostvars[inventory_hostname].ansible_default_ipv4.address }} {{ hostmaster_fqdn }}" state=present
    when: hostvars[inventory_hostname].ansible_default_ipv4.address is defined

  - name: Check if Aegir is installed
    stat: 
      path: "{{ aegir_user_home }}/config"
    register: aegir_installed

  - include: install_aegir.yml
    # when: not aegir_installed.stat.exists
